name: Deploy express server

on:
  push:
    branches: 
      - main

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t parkingsoftware/backend .
      - name: Publish Image to Docker hub
        run: docker push parkingsoftware/backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps: 
      - name: Pull Image from Docker hub 
        run: docker pull parkingsoftware/backend:latest
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name parking-software -e MONGODB_URI='${{ secrets.MONGO_URI }}' parkingsoftware/backend:latest